### ISSUE TITLE
Demo for Bank statement

### ISSUE THREAD

**Issue by xianbinKit** [eCollect/node-ebics-client#18]
Hello, 

May I have an example how to receive banque statement daily  ?  automatically ?

Thank you

**Comment by nanov** [comment]
Receiving a daily statement can be achieved by executing either ```CAMT53``` or the ```STA``` orders against your bank, which one depends on your bank.

This will download the available statements for the specified period, data will be available inside ```result.orderData``` property.

Persisting, probably unzipping and parsing the statements is a task that is out of scope of this library.

As of "automatically", I don't really understand what you mean, but any further tasks/schedules/automations are up to you to implement.

**Comment by Herrie82** [comment]
Some more statement examples were added by https://github.com/node-ebics/node-ebics-client/pull/48

Any further automation you would need to script yourself and you can schedule it with your task scheduler.
