### ISSUE TITLE
Getting 091008 - EBICS_BANK_PUBKEY_UPDATE_REQUIRED for upload orders

### ISSUE THREAD

**Issue by vasyas** [eCollect/node-ebics-client#2]
I am getting `091008 - [EBICS_BANK_PUBKEY_UPDATE_REQUIRED] Bank key invalid` error on upload orders, CCT for example.

Download orders are working ok.
Refetching bank keys don't help.

Connecting to Handelsbanken, if that matters.

**Comment by nanov** [comment]
Hi,

Is [that the bank](https://www.handelsbanken.com/en/) that you are trying with?
What orders exactly are problematic?
Does it has EBICS specification/documentation?
Does it has a test-platform against some tests can be run?

I am sorry i cannot provide more data, but as every bank have it's quirks in the way they've implemented the EBICS standard this things matter.

**Comment by vladhristov** [comment]
Hi from me too @vasyas ,

I've tried the order myself but our bank's test platform doesn't support CCT orders yet. I changed the order's name to XE2 for example, and send the same xml file. No problems occurred.

Can you show some sample code, like how do you build the order and the xml document for the CCT order?

Regards,
Vlad

**Comment by vasyas** [comment]
@vladhristov @nanov Thanks for your replies.

My code for CCT is pretty much the same as for other orders:
```
    const client = new Client({
        url: "https://ebics.handelsbank.com/ebicsprod",
        partnerId: <skipped>,
        userId: <skipped>,
        hostId: "SBKPR01",
        passphrase: <skipped>,
        keyStorage: fsKeysStorage("./ebics/keys"),
        tracesStorage: tracesStorage("../ebics-logs"),
    })

   const r = await client.send(Orders.CCT(<XML content skipped>))
```
It works for download orders, but not working for CCT. 

Do you know, this `Bank key invalid` error - is it related to signing the EBICS message or it could be smth with the actual uploaded content?

**Comment by vasyas** [comment]
@vladhristov @nanov 
Found an issue with bank keys parsing.
I've made a fix and test case demoing parsing errors, please see PR #3.

BTW, thanks for the awesome lib - it was really easy to make the fix.

**Comment by nanov** [comment]
PR is merged and released, is the original issue solved with this PR?

**Comment by vasyas** [comment]
Thanks.
It is closed.
