### ISSUE TITLE
Demo EBICS server

### ISSUE THREAD

**Issue by andrew-svirin** [eCollect/node-ebics-client#8]
Hi,

I try to implement EBICS on PHP and got the proble,
Have you an address of demo-server for test ebics protocol? Or how do you testing requests?

**Comment by nanov** [comment]
If you don’t target specific bank, I would suggest starting with [Credit Suisse Test Platform](https://iso20022test.credit-suisse.com/register) as it is well documented and as closest to the standard.

**Comment by andrew-svirin** [comment]
@nanov thanks a lot
